global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "order-service"
    scheme: https
    static_configs:
      - targets: ["order-service-mk1g.onrender.com"]

  - job_name: "tracking-service"
    scheme: https
    static_configs:
      - targets: ["tracking-service-0s1v.onrender.com"]

  - job_name: "notification-service"
    scheme: https
    static_configs:
      - targets: ["notification-service-ahzu.onrender.com"]

rule_files:
  - "alerts.yml"
