services:
  order-service:
    build: ./order-service
    ports:
      - "${ORDER_SERVICE_PORT}:3001"
    environment:
      - PORT=3001
    env_file:
      - .env
    networks:
      - watchtower-net

  tracking-service:
    build: ./tracking-service
    ports:
      - "${TRACKING_SERVICE_PORT}:3002"
    environment:
      - PORT=3002
    env_file:
      - .env
    networks:
      - watchtower-net

  notification-service:
    build: ./notification-service
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:3003"
    environment:
      - PORT=3003
    env_file:
      - .env
    networks:
      - watchtower-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - watchtower-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - watchtower-net      

networks:
  watchtower-net:
    driver: bridge