services:
  - type: web
    name: order-service
    runtime: docker
    rootDir: dev-ops/WatchTower/app
    dockerfilePath: ./order-service/Dockerfile
    dockerContext: ./order-service
    plan: free
    envVars:
      - key: PORT
        value: 3001

  - type: web
    name: tracking-service
    runtime: docker
    rootDir: dev-ops/WatchTower/app
    dockerfilePath: ./tracking-service/Dockerfile
    dockerContext: ./tracking-service
    plan: free
    envVars:
      - key: PORT
        value: 3002

  - type: web
    name: notification-service
    runtime: docker
    rootDir: dev-ops/WatchTower/app
    dockerfilePath: ./notification-service/Dockerfile
    dockerContext: ./notification-service
    plan: free
    envVars:
      - key: PORT
        value: 3003

  - type: web
    name: prometheus
    runtime: image
    image:
      url: docker.io/prom/prometheus:latest
    plan: free

  - type: web
    name: grafana
    runtime: image
    image:
      url: docker.io/grafana/grafana:latest
    plan: free
    envVars:
      - key: GF_SECURITY_ADMIN_PASSWORD
        value: admin
